apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
  namespace: svc-account
spec:
  predictor:
    serviceAccountName: sa-s3-access
    model:
      modelFormat:
        name: sklearn
      storageUri: s3://mlops-churn-akuldevali/models/churn_model.pkl